# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    configuration: 'Release'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Default(5b561054-bfea-47ab-b596-35495e57e0d5)'
    appType: 'webApp'
    WebAppName: 'open-api-hub'
    packageForLinux: '$(System.DefaultWorkingDirectory)/OpenHubCollaborationHub/OpenHubCollaborationHub/bin/Debug/net6.0/publish/'